replicaCount: 2

image:
  repository: faizanabuzar/go-web-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: k88pro.devfaizi.xyz
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # EKS ALB Controller annotations (uncomment if using ALB)
    # kubernetes.io/ingress.class: alb
    # alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: ip

app:
  name: go-web-app
  port: 8080