name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build application
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Run tests
      run: go test -v ./...

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          faizanabuzar/go-web-app:${{ github.run_number }}
          faizanabuzar/go-web-app:latest

  helm-update:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update Helm values
      run: |
        sed -i 's|tag: .*|tag: "${{ github.run_number }}"|' values.yaml
    - name: Commit updated Helm chart
      run: |
        git config --local user.email "faizanabuzar@hotmail.com"
        git config --local user.name "Faizan Abuzar"
        git add values.yaml
        git commit -m "Update image tag to ${{ github.run_number }}" || exit 0
        git push